[build]
  cmd = "swag init -g cmd/server/main.go && go build -o ./tmp/main ./cmd/server"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["docs", "tmp", "vendor"]